### ISSUE TITLE
Edit HW Specs

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/OVZ#1]
Bearbeiten und Verändern von Cores, Memory und Speicherplatz

**Comment by rnt-ash** [comment]
@rnt-maple Bug: Wenn description gesetzt ist und durch den Job auf einen leeren String gesetzt wird, scheint das Programm die description nicht neu zu setzten (auf Seite des Hostservers).

**Comment by rnt-maple** [comment]
Es scheint so, als ob der prlctl Befehl die description nicht auf einen leeren String zurücksetzt, wenn man einen leeren String angibt:
![image](https://cloud.githubusercontent.com/assets/8237225/23396671/297a11f2-fd95-11e6-9f13-c24c6eb7eeda.png)

Eine mögliche Alternative wäre die Angabe eines leeren Strings mit einem Whitespace (getestet, funktioniert als Workaround)
- entweder erst unten im auf dem Host einen leeren String zu einem " " umwandeln
- oder schon in OVZCP eine leere Description als " " übergeben

@rnt-oak wäre das annehmbar?

**Comment by rnt-maple** [comment]
Da es sich eher um einen Bug in prlctl handelt, würde ich dazu tendieren die Änderung so nah wie möglich am prlctl Befehl zu machen und da zu begründen, und zwar folgendermassen:
![image](https://cloud.githubusercontent.com/assets/8237225/23397430/c859b98c-fd98-11e6-9dc5-25c709112283.png)
