### ISSUE TITLE
Job für verteilen von root-ssh-public-keys für authorized_keys

### ISSUE THREAD

**Issue by rnt-maple** [RNT-Forest/OVZ#16]
Betrifft (momentan) nur die PhysicalServers, welche ovz=1 sind.

wird z.B. für migration benötigt zwischen PhysicalServers benötigt

evt. diesen Job immer gleich beim Connecten hinterherschicken (an alle PhysicalServers wo ovz=1)

**Comment by rnt-maple** [comment]
im gleichen Zug soll auch ein Job gemacht werden, der die Abfrage des root-ssh-public-keys erlaubt

**Comment by rnt-maple** [comment]
Es gibt nun im Administrations-Bereich einen Button für die Verteilung der Keys auf allen PhysicalServers. Dabei wird zuerst für jeden Server der entsprechende key aktualisiert und dann alle gemeinsam geschickt. Somit hat halt jeder Server seinen eigenen Public-Key auch im authorized_key file, doch dies sollte ja nicht schlimm sein.

Nach dem Connector wird nicht automatisch alles verteilt, da dies doch ein paar Sekunden dauert und mit steigender Anzahl Server noch länger geht.

**Comment by rnt-maple** [comment]
Was natürlich in der aktuellen Entwicklungs-Situation, wo jeder ein paar andere PhysicalServer im eigenen OVZCP hat, teilweise zu Problemen führen könnte. Immer der, der zuletzt diese Aktion ausführt, löscht dann in allen authorized_key Files alle Zeilen, welche den Substring "[ovz]" beinhalten und schreibt die im eigenen OVZCP geholten Keys neu rein. Dann kann es passieren, dass jemand mit weniger connecteten Servern einem anderen die Arbeit schwer macht, indem er die ihm fehlenden Keys weglöscht.

**Comment by rnt-oak** [comment]
Das System ist aber für diesen Einsatzzweck nicht gedacht uns sollte somit nicht so verwendet werden.
Allenfalls muss ein zentrales Entwicklersystem erstellt werden, wo alle mitarbeiten...
