### ISSUE TITLE
New Server (CT, VM) Pending, obwohl es das Gerät noch gar nicht gibt

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/OVZ#20]
Das Gerät wird ja im Hintergrund erstellt und sollte nicht bearbeitet werden können, solange die Erstellung nicht fertig ist.

**Comment by rnt-maple** [comment]
Da für Pending die Entity in der DB existieren muss, müsste der executeJob im postSave des VirtualControllerBase gemacht werden.
