### ISSUE TITLE
MonLocalJob Konzept

### ISSUE THREAD

**Issue by rnt-maple** [RNT-Forest/OVZ#29]
- unterscheiden sich von MonRemoteJob, da diese LocalJobs zur Ausführung als "Job" per Push Service an den Server geschickt werden und da sozusagen lokal monitoren...
- Pro Ausführung wird ein Job geschickt (gibt dann halt viele Jobs, sollen im Jobs GUI evt ausgeblendet werden können? gehört dann aber eher ins core-Project, wo man definieren könnte welche Job-Typen man nicht darstellen würde)
- Ziel ist es den schon existierenden Jobtyp ovz_statistics_info zum Erhalt der Daten zu verwenden

**Comment by rnt-maple** [comment]
Problem: Mit grosser Wahrscheinlichkeit wird EIN Server auf CPU, Disk und RAM gemonitort. Im ovz_statistics_info Job kommen schon Daten zu all diesen Punkten zurück. Es wäre ja nun unsinnig für jeden Fall (CPU, Disk, RAM) einen neuen Job abzuschicken. Doch welcher Fall löst den Job aus? Kommen die MonLocalJobs nacheinander? Dies ist nicht klar definierbar. 

Vorschlag: Grundsätzlich liest ein MonLocalJobs die Werte aus ovz_statistics aus der Datenbank, also dem Physical bzw. VirtualServers Model. Ist der Wert von modified älter als z.B. eine Minute, dann wird ein entsprechender Job zum Updaten des ovz_statistics Feld geschickt.


Folgeproblem: Wie wird dieser Job zum Updaten des statistics Feld geschickt? Man hat ja Physical und VirtualServers und die haben unterschiedliche Job Typen für diesen Fall?

Vorschlag 1: Im MonServerInterface gibt es die getParentClass Methode, mit welcher man eruieren könnte welchen Job man wohin schicken müsste
Vorschlag 2: Neue Methode im MonServerInterface die das ovz_statistics Feld updatet inkl. entsprechendem Job.

**Comment by rnt-maple** [comment]
Wurde entsprechend den Vorschlägen umgesetzt

Am Anfang werden alle Statistiken neu geholt, würde die Ausführung länger dauern und eine Minute würde verstreichen, so würden die entsprechenden MonJobs die Statistiken erneut holen. Es wird auf das modified geschaut.

Der Job zum Updaten des Statistik-Felds wird in einer neuen Methode implementiert, welche auch im MonServerInterface hinzugefügt wurde.

**Comment by rnt-maple** [comment]
wurde am Beispiel von Cpu eines Virtual Servers umgesetzt. Der ganze Rest muss noch implementiert werden.

**Comment by rnt-maple** [comment]
Es soll nicht auf das modified des Server Elements geschaut werden, sondern auf das modified IM ovz_statistics JSON drin

**Comment by rnt-oak** [comment]
ovz_statistics und ovz_settings geben jetzt auch einen Timestamp zurück
