### ISSUE TITLE
Datumsberechnungen mit der PHP Bibliothek

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/OVZ#35]
Für die Berechnungen von Daten bitte diese Funktionen benützen: http://php.net/manual/de/ref.datetime.php

**Comment by rnt-maple** [comment]
diese Funktionen werden ja bereits verwendet für die Datumsberechnungen?

Es werden Funktionen von [Helpers](https://github.com/RNT-Forest/CORE/blob/develop/libraries/Helpers.php) gecallt, welche intern dann mit date oder mktime umrechnen.

Dies unter anderem mit dem Ziel, dass der Code einfacher lesbar ist, also im Methodennamen steht was es macht.

**Comment by rnt-maple** [comment]
wird grundsätzlich also bereits so gemacht. Beim Arbeiten im Code wird ein spezielles Augenmerk darauf gelegt und allenfalls angepasst. Den Issue schliesse ich also wieder.
