### ISSUE TITLE
Diskspace in GB

### ISSUE THREAD

**Issue by rnt-maple** [RNT-Forest/OVZ#43]
Im Model von Virtual und PhysicalServers sollte der Space in GB angegeben werden und nicht in MB.

Im Monitoring wird dies schon so gehandhabt, doch im Model (und den entsprechenden Controllern, Views) noch nicht bzw. nicht genügend klar. Man müsste dies also komplett durchziehen, prüfen ob es wirklich stimmt in sich.

Der View darf die Ausgabe schon in MB, GB oder TB umrechnen, doch sobald damit gerechnet wird, also insbesondere innerhalb des Models oder wenn man es mit den settern im Model setzt, soll der Wert als GB angeschaut werden.

**Comment by rnt-oak** [comment]
Aus meiner Sicht sollte dies jetzt überall beachtet worden sein?

**Comment by rnt-maple** [comment]
Nein, ist immer noch das Problem:
![image](https://cloud.githubusercontent.com/assets/8237225/25791976/1c3b1f76-33c4-11e7-8224-326747a69748.png)
in der DB steht 300GB und im View steht 300MB
![image](https://cloud.githubusercontent.com/assets/8237225/25791985/26dd706e-33c4-11e7-86c6-2981db4bda9c.png)

**Comment by rnt-maple** [comment]
Es ist sogar noch prekärer als gedacht, würde man auf einem Server, der 300GB Platz hat und dies im Model auch so vermerkt ist, das Configure Formular laden, dann würde durch das Holen der Infos zum Gast über den Physical im Model der diskspace auf 307200 gesetzt, was dann ja im Model 300TB wären.

**Comment by rnt-maple** [comment]
offener Punkt ist noch in #64 separat gelistet
