### ISSUE TITLE
GUI Auflisten von vorhandenen MonJobs

### ISSUE THREAD

**Issue by rnt-maple** [RNT-Forest/OVZ#45]
Details siehe Papier

**Comment by rnt-ash** [comment]
Behavior wird im Moment noch unschön dargestellt. Statische Methode um nur den Namen und nicht die ganze Klasse auszulesen konnte nicht per Volt aufgerufen werden.

**Comment by rnt-maple** [comment]
das Ganze Darstellen der MonJobs muss noch überarbeitet werden. ich werde dazu noch weitere Informationen erarbeiten
