### ISSUE TITLE
Delete Virtual Server ermöglichen, wenn das Gastsystem nicht vorhanden ist.

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/OVZ#60]
Ein Virtual Server soll dann aus der Datenbank gelöscht werden, wenn zwar einen ovz_uuid vorhanden ist, aber das entsprechende Gastsysten auf den Hosts nicht vorhanden ist. Ansonsten ist es nicht möglich ein von Hand gelöschtes Gastsystem aus der DB zu entfernen.

**Comment by rnt-ash** [comment]
Wurde erledigt.
