### ISSUE TITLE
Edit Form von Physical und VirtualServers formatiert Bytewerte nicht

### ISSUE THREAD

**Issue by rnt-maple** [RNT-Forest/OVZ#64]
das Standard-Edit-Form formatiert die Bytewerte nicht, es werden also in Rohform die Werte aus dem Model einfach ausgegeben, für Memory wäre das z.B. dann bei 16GB die Zahl "16384". Wie kann man diese Werte zur Anzeige durch den formatBytes-Helper lassen?

PS: Der Controller kann beim Speichern sowohl mit den Rohzahlen umgehen, als auch wenn man ein Byte-Suffix angeben würde. Dafür wird im preSave() eine entsprechende Selektion und Konversion vorgenommen. Bei Rohzahlen interpretiert der Controller für Memory die Zahl in MB und bei Space in GB.

**Comment by rnt-ash** [comment]
Wurde bei Virtual Server gemacht, bei Physical Server jedoch noch nicht. @rnt-oak Soll dies noch gemacht werden?
