### ISSUE TITLE
Replika Statistiken anzeigen

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/OVZ#72]
Neuer Knopf erstellen, indem man ein Datum (Tag) auswählen kann um die Replika Statistiken von diesem Tag anzuzeigen.
![image](https://user-images.githubusercontent.com/8237230/27226741-ba28168a-52a0-11e7-8ea4-8a77c5bbc9e7.png)
Knopf soll nur von Logins mit Permission "general:*" gesehen und ausgeführt werden können.
Funktion \RNTForest\ovz\services\Replica::tryGetStats($date); liefert ein Array mit allen benötigten Daten.

Ausgabe eines übersichtlich und ansprechend gestalteten PDF von diesem Tag mit einer Übersicht der ausgeführten Replikas. 
Spalten: Name des Replika Masters, Name des Replika Slave, Startzeit, Endzeit, Dauer, Anzahl übertragener Files, Anzahl übertragene Bytes (MB,GB usw.)

**Comment by rnt-ash** [comment]
Mit @rnt-elm (Reto) besprochen -> soweit OK. 
Genaueres wird sich im produktiven Einsatz zeigen.
