### ISSUE TITLE
MonJobs mon_type local nur für OpenVZ connectete Physicals bzw. VirtualServer auf solchigen

### ISSUE THREAD

**Issue by rnt-maple** [RNT-Forest/OVZ#75]
local MonJobs verwenden Informationen aus ovz_statistics. Dieses Feld hat nur Daten, wenn der Server entweder: 
- ein PhysicalServers Objekt mit ovz = 1
- oder ein VirtualServers Objekt mit einem parent PhysicalServers Objekt mit ovz = 1

ist. Deshalb sollten im GUI-Formular zum Hinzufügen neuer MonJobs nur die local MonJobs zur Auswahl stehen, die überhaupt möglich sind.

**Comment by rnt-ash** [comment]
@rnt-maple Sollen gar keine local MonJobs aufgelistet werden oder nur ein paar spezielle nicht?
Wenn nur ein paar, welche genau?

**Comment by rnt-maple** [comment]
@rnt-ash Local MonJobs gibt es nur für connectete Hosts bzw. Virtuals auf connecteten Hosts. Demnach gar keine Local MonJobs auflisten
